name: verify-ci-status
description: Verifies that a CI status is passing before proceeding.
inputs:
  GITHUB_TOKEN:
    description: Token to run with, defaults to the repository GITHUB_TOKEN
    required: true
  output_result:
    description: Outputs the result as 'result = passed' if check is passed or an error result if not
    required: false
  name:
    required: false
    description: Name of the check to validate against
    default: Jenkins
runs:
  using: composite
  steps: 
    - run: GITHUB_TOKEN=${{ inputs.GITHUB_TOKEN }} OUTPUT_RESULT=${{ inputs.output_result }} NAME=${{ inputs.name }} $GITHUB_ACTION_PATH/run.sh
      shell: bash
